# Use the official node image as a parent image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package files first to leverage Docker cache
COPY package.json yarn.lock ./
RUN yarn install

# Then copy the rest of the files
COPY . .

# Compile the fairmint-canton/scripts submodule
RUN cd src/chain-operations/canton/lib/fairmint-canton/scripts && yarn install && yarn build

EXPOSE 8080
CMD ["yarn", "dev"]
